//THIS FILE IS AUTOMATICALLY GENERATED BY DOGMOS, PLEASE DO NOT TOUCH IT
//PROC DEFINITIONS MAY MOVE AROUND, THIS IS NORMAL

/* This comment bypasses grep checks */ /var/__dogmos

/proc/__detect_dogmos()
	if (world.system_type == UNIX)
		return __dogmos = "libdogmos"
	else
		return __dogmos = "dogmos"

#define DOGMOS (__dogmos || __detect_dogmos())

/// Returns: If this cycle is interrupted by overtiming or not. Starts a katmos equalize cycle, does nothing if process_turfs isn't ran.
/datum/controller/subsystem/air/proc/process_turf_equalize_auxtools(remaining)
	var/static/loaded = load_ext(DOGMOS, "byond:equalize_hook_ffi")
	return call_ext(loaded)(src, remaining)

/// Updates adjacency infos for turfs, only use this in immediateupdateturfs.
/turf/proc/__update_auxtools_turf_adjacency_info()
	var/static/loaded = load_ext(DOGMOS, "byond:hook_infos_ffi")
	return call_ext(loaded)(src)

/// Returns: null. Updates turf air infos, whether the turf is closed, is space or a regular turf, or even a planet turf is decided here.
/turf/proc/update_air_ref(flag)
	var/static/loaded = load_ext(DOGMOS, "byond:hook_register_turf_ffi")
	return call_ext(loaded)(src, flag)

/// Args: (holder). Runs all reactions on this gas mixture. Holder is used by the reactions, and can be any arbitrary datum or null.
/// Underscored because DM keeps a `react()` wrapper of its own, carrying behaviour Dogmos has no
/// equivalent for: the hypernoblium oppression gate that stops all reactions before any are
/// considered, the reaction_results bookkeeping, and COMSIG_GASMIX_REACTED.
/datum/gas_mixture/proc/__react(holder)
	var/static/loaded = load_ext(DOGMOS, "byond:react_hook_ffi")
	return call_ext(loaded)(src, holder)

/// Returns: true if the two mixtures are different enough for processing, false otherwise.
/datum/gas_mixture/proc/compare(other)
	var/static/loaded = load_ext(DOGMOS, "byond:compare_hook_ffi")
	return call_ext(loaded)(src, other)

/// Clears the gas mixture my removing all of its gases.
/datum/gas_mixture/proc/clear()
	var/static/loaded = load_ext(DOGMOS, "byond:clear_hook_ffi")
	return call_ext(loaded)(src)

/// Returns: whether the mix has been marked immutable.
///
/// Meridian: added because remove_into/remove_ratio_into do not themselves check immutability -
/// only merge and copy_from_mutable do - so removing gas from an immutable mixture (e.g. a space
/// tile) would silently deplete it over time. DM's __remove/__remove_ratio wrappers check this
/// first and return an inexhaustible copy instead of draining space, matching upstream tg's
/// `/datum/gas_mixture/immutable/space/remove()` behaviour.
/datum/gas_mixture/proc/is_immutable()
	var/static/loaded = load_ext(DOGMOS, "byond:is_immutable_hook_ffi")
	return call_ext(loaded)(src)

/// Marks the mix as immutable, meaning it will never change. This cannot be undone.
/datum/gas_mixture/proc/mark_immutable()
	var/static/loaded = load_ext(DOGMOS, "byond:mark_immutable_hook_ffi")
	return call_ext(loaded)(src)

/// Args: (mixture, ratio, gas_list). Takes gases given by `gas_list` and moves `ratio` amount of those gases from `src` into `mixture`.
/datum/gas_mixture/proc/scrub_into(into, ratio_v, gas_list)
	var/static/loaded = load_ext(DOGMOS, "byond:scrub_into_hook_ffi")
	return call_ext(loaded)(src, into, ratio_v, gas_list)

/// Args: (flag). As get_gases(), but only returns gases with the given flag.
/datum/gas_mixture/proc/get_by_flag(flag_val)
	var/static/loaded = load_ext(DOGMOS, "byond:get_by_flag_hook_ffi")
	return call_ext(loaded)(src, flag_val)

/// Args: (mixture, flag, amount). Takes `amount` from src that have the given `flag` and puts them into the given `mixture`. Returns: 0 if gas didn't have any with that flag, 1 if it did.
/datum/gas_mixture/proc/__remove_by_flag(into, flag_val, amount_val)
	var/static/loaded = load_ext(DOGMOS, "byond:remove_by_flag_hook_ffi")
	return call_ext(loaded)(src, into, flag_val, amount_val)

/// Args: (coefficient). Divides all gases by this amount.
/datum/gas_mixture/proc/divide(num_val)
	var/static/loaded = load_ext(DOGMOS, "byond:divide_hook_ffi")
	return call_ext(loaded)(src, num_val)

/// Args: (coefficient). Multiplies all gases by this amount.
/datum/gas_mixture/proc/multiply(num_val)
	var/static/loaded = load_ext(DOGMOS, "byond:multiply_hook_ffi")
	return call_ext(loaded)(src, num_val)

/// Args: (amount). Subtracts the given amount from each gas.
/datum/gas_mixture/proc/subtract(num_val)
	var/static/loaded = load_ext(DOGMOS, "byond:subtract_hook_ffi")
	return call_ext(loaded)(src, num_val)

/// Args: (amount). Adds the given amount to each gas.
/datum/gas_mixture/proc/add(num_val)
	var/static/loaded = load_ext(DOGMOS, "byond:add_hook_ffi")
	return call_ext(loaded)(src, num_val)

/// Args: (gas_id_1, amount_1, gas_id_2, amount_2, ...). As adjust_moles, but with variadic arguments.
/// Raw FFI bind - gas ids must already be Dogmos' string form. Use adjust_multi() in gas_mixture.dm.
/datum/gas_mixture/proc/__adjust_multi(...)
	var/list/args_copy = args.Copy()
	args_copy.Insert(1, src)
	var/static/loaded = load_ext(DOGMOS, "byond:adjust_multi_hook_ffi")
	return call_ext(loaded)(arglist(args_copy))

/// Args: (gas_id, moles, temp). Adjusts the given gas's amount by the given amount, with that gas being treated as if it is at the given temperature.
/// Raw FFI bind - gas_id must already be Dogmos' string form. Use adjust_moles_temp() in gas_mixture.dm.
/datum/gas_mixture/proc/__adjust_moles_temp(id_val, num_val, temp_val)
	var/static/loaded = load_ext(DOGMOS, "byond:adjust_moles_temp_hook_ffi")
	return call_ext(loaded)(src, id_val, num_val, temp_val)

/// Args: (gas_id, moles). Adjusts the given gas's amount by the given amount, e.g. (GAS_O2, -0.1) will remove 0.1 moles of oxygen from the mixture.
/// Raw FFI bind - id_val must already be Dogmos' string form. Use adjust_moles() in gas_mixture.dm.
/datum/gas_mixture/proc/__adjust_moles(id_val, num_val)
	var/static/loaded = load_ext(DOGMOS, "byond:adjust_moles_hook_ffi")
	return call_ext(loaded)(src, id_val, num_val)

/// Args: (gas_id, moles). Sets the amount of substance of the given gas, in moles.
/// Raw FFI bind - gas_id must already be Dogmos' string form. Use set_moles() in gas_mixture.dm.
/datum/gas_mixture/proc/__set_moles(gas_id, amt_val)
	var/static/loaded = load_ext(DOGMOS, "byond:set_moles_hook_ffi")
	return call_ext(loaded)(src, gas_id, amt_val)

/// Args: (gas_id). Returns: the amount of substance of the given gas, in moles.
/// Raw FFI bind - gas_id must already be Dogmos' string form. Use get_moles() in gas_mixture.dm.
/datum/gas_mixture/proc/__get_moles(gas_id)
	var/static/loaded = load_ext(DOGMOS, "byond:get_moles_hook_ffi")
	return call_ext(loaded)(src, gas_id)

/// Args: (volume). Sets the volume of the gas.
/datum/gas_mixture/proc/set_volume(vol_arg)
	var/static/loaded = load_ext(DOGMOS, "byond:set_volume_hook_ffi")
	return call_ext(loaded)(src, vol_arg)

/// Args: (gas_id). Returns the heat capacity from the given gas, in J/K (probably).
/// Raw FFI bind - gas_id must already be Dogmos' string form. Use partial_heat_capacity() in gas_mixture.dm.
/datum/gas_mixture/proc/__partial_heat_capacity(gas_id)
	var/static/loaded = load_ext(DOGMOS, "byond:partial_heat_capacity_ffi")
	return call_ext(loaded)(src, gas_id)

/// Args: (temperature). Sets the temperature of the mixture. Will be set to 2.7 if it's too low.
/datum/gas_mixture/proc/set_temperature(arg_temp)
	var/static/loaded = load_ext(DOGMOS, "byond:set_temperature_hook_ffi")
	return call_ext(loaded)(src, arg_temp)

/// Returns: a list of the gases in the mixture, associated with their IDs.
/// Raw FFI bind - returns Dogmos' native string ids. Use get_gases() in gas_mixture.dm, which
/// translates back to the typepaths every DM call site expects.
/datum/gas_mixture/proc/__get_gases()
	var/static/loaded = load_ext(DOGMOS, "byond:get_gases_hook_ffi")
	return call_ext(loaded)(src)

/// Args: (src, mixture, conductivity) or (src, conductivity, temperature, heat_capacity). Adjusts temperature of src based on parameters. Returns: temperature of sharer after sharing is complete.
/datum/gas_mixture/proc/temperature_share(...)
	var/list/args_copy = args.Copy()
	args_copy.Insert(1, src)
	var/static/loaded = load_ext(DOGMOS, "byond:temperature_share_hook_ffi")
	return call_ext(loaded)(arglist(args_copy))

/// Arg: (mixture). Makes src into a copy of the argument mixture.
/datum/gas_mixture/proc/copy_from(giver)
	var/static/loaded = load_ext(DOGMOS, "byond:copy_from_hook_ffi")
	return call_ext(loaded)(src, giver)

/// Args: (mixture, amount). Takes the given amount of gas from src and puts it into the argument mixture. Amount is amount of substance in moles.
/datum/gas_mixture/proc/__remove(into, amount_arg)
	var/static/loaded = load_ext(DOGMOS, "byond:remove_hook_ffi")
	return call_ext(loaded)(src, into, amount_arg)

/// Args: (mixture, ratio). Takes the given ratio of gas from src and puts it into the argument mixture. Ratio is a number between 0 and 1.
/datum/gas_mixture/proc/__remove_ratio(into, ratio_arg)
	var/static/loaded = load_ext(DOGMOS, "byond:remove_ratio_hook_ffi")
	return call_ext(loaded)(src, into, ratio_arg)

/// Args: (mixture). Merges the gas from the giver into src, without modifying the giver mix.
/// Underscored because DM keeps a `merge()` wrapper of its own: it sends COMSIG_GASMIX_MERGED,
/// which gas tanks and the atmos reaction recorder listen for, and returns a success boolean.
/datum/gas_mixture/proc/__merge(giver)
	var/static/loaded = load_ext(DOGMOS, "byond:merge_hook_ffi")
	return call_ext(loaded)(src, giver)

/// Returns: true. Parses gas strings like "o2=2500;plasma=5000;TEMP=370" and turns src mixes into the parsed gas mixture, invalid patterns will be ignored
/datum/gas_mixture/proc/__auxtools_parse_gas_string(string)
	var/static/loaded = load_ext(DOGMOS, "byond:parse_gas_string_ffi")
	return call_ext(loaded)(src, string)

/// Returns: the total amount of gas mixtures in the arena, including "free" ones.
/datum/controller/subsystem/air/proc/get_max_gas_mixes()
	var/static/loaded = load_ext(DOGMOS, "byond:hook_max_gas_mixes_ffi")
	return call_ext(loaded)()

/// Returns: the amount of gas mixtures that are attached to a byond gas mixture.
/datum/controller/subsystem/air/proc/get_amt_gas_mixes()
	var/static/loaded = load_ext(DOGMOS, "byond:hook_amt_gas_mixes_ffi")
	return call_ext(loaded)()

/// Args: (list). Takes every gas in the list and makes them all identical, scaled to their respective volumes. The total heat and amount of substance in all of the combined gases is conserved.
/proc/equalize_all_gases_in_list(gas_list)
	var/static/loaded = load_ext(DOGMOS, "byond:equalize_all_hook_ffi")
	return call_ext(loaded)(gas_list)

/// Args: (temperature). Returns: how much oxidizer for fire is in the mixture at the given temperature. If temperature is omitted, just uses current temperature instead.
/datum/gas_mixture/proc/get_oxidation_power(temp)
	var/static/loaded = load_ext(DOGMOS, "byond:oxidation_power_hook_ffi")
	return call_ext(loaded)(src, temp)

/// Args: (temperature). Returns: how much fuel for fire is in the mixture at the given temperature. If temperature is omitted, just uses current temperature instead.
/datum/gas_mixture/proc/get_fuel_amount(temp)
	var/static/loaded = load_ext(DOGMOS, "byond:fuel_amount_hook_ffi")
	return call_ext(loaded)(src, temp)

/// Args: (mixture). Makes `src` a copy of `mixture`, with volumes taken into account.
/datum/gas_mixture/proc/equalize_with(total)
	var/static/loaded = load_ext(DOGMOS, "byond:equalize_with_hook_ffi")
	return call_ext(loaded)(src, total)

/// Args: (mixture, ratio). Transfers `ratio` of `src` to `mixture`.
/datum/gas_mixture/proc/transfer_ratio_to(other, ratio)
	var/static/loaded = load_ext(DOGMOS, "byond:transfer_ratio_hook_ffi")
	return call_ext(loaded)(src, other, ratio)

/// Args: (mixture, amount). Takes the `amount` given and transfers it from `src` to `mixture`.
/datum/gas_mixture/proc/transfer_to(other, moles)
	var/static/loaded = load_ext(DOGMOS, "byond:transfer_hook_ffi")
	return call_ext(loaded)(src, other, moles)

/// Args: (heat). Adds a given amount of heat to the mixture, i.e. in joules taking into account capacity.
/datum/gas_mixture/proc/adjust_heat(temp)
	var/static/loaded = load_ext(DOGMOS, "byond:adjust_heat_hook_ffi")
	return call_ext(loaded)(src, temp)

/// Returns: the mix's thermal energy, the product of the mixture's heat capacity and its temperature.
/datum/gas_mixture/proc/thermal_energy()
	var/static/loaded = load_ext(DOGMOS, "byond:thermal_energy_hook_ffi")
	return call_ext(loaded)(src)

/// Returns: the mix's volume, in liters.
/datum/gas_mixture/proc/return_volume()
	var/static/loaded = load_ext(DOGMOS, "byond:return_volume_hook_ffi")
	return call_ext(loaded)(src)

/// Returns: the mix's temperature, in kelvins.
/datum/gas_mixture/proc/return_temperature()
	var/static/loaded = load_ext(DOGMOS, "byond:return_temperature_hook_ffi")
	return call_ext(loaded)(src)

/// Returns: the mix's pressure, in kilopascals.
/datum/gas_mixture/proc/return_pressure()
	var/static/loaded = load_ext(DOGMOS, "byond:return_pressure_hook_ffi")
	return call_ext(loaded)(src)

/// Returns: Amount of substance, in moles.
/datum/gas_mixture/proc/total_moles()
	var/static/loaded = load_ext(DOGMOS, "byond:total_moles_hook_ffi")
	return call_ext(loaded)(src)

/// Args: (min_heat_cap). Sets the mix's minimum heat capacity.
/datum/gas_mixture/proc/set_min_heat_capacity(arg_min)
	var/static/loaded = load_ext(DOGMOS, "byond:min_heat_cap_hook_ffi")
	return call_ext(loaded)(src, arg_min)

/// Returns: Heat capacity, in J/K (probably).
/datum/gas_mixture/proc/heat_capacity()
	var/static/loaded = load_ext(DOGMOS, "byond:heat_cap_hook_ffi")
	return call_ext(loaded)(src)

/// Adds the gas mixture's ID to the queue of mixtures that have been deleted, to be reused later.
/// This version is only if auxcleanup is not being used; it should be called from /datum/gas_mixture/Del.
/datum/gas_mixture/proc/__gasmixture_unregister()
	var/static/loaded = load_ext(DOGMOS, "byond:unregister_gasmixture_hook_ffi")
	return call_ext(loaded)(src)

/// Fills in the first unused slot in the gas mixtures vector, or adds another one, then sets the argument ByondValue to point to it.
/datum/gas_mixture/proc/__gasmixture_register()
	var/static/loaded = load_ext(DOGMOS, "byond:register_gasmixture_hook_ffi")
	return call_ext(loaded)(src)

/// Args: (ms). Runs callbacks until time limit is reached. If time limit is omitted, runs all callbacks.
/proc/process_atmos_callbacks(remaining)
	var/static/loaded = load_ext(DOGMOS, "byond:atmos_callback_handle_ffi")
	return call_ext(loaded)(remaining)

/// Returns: If this cycle is interrupted by overtiming or not. Starts a processing excited groups cycle, does nothing if process_turfs isn't ran.
/datum/controller/subsystem/air/proc/process_excited_groups_auxtools(remaining)
	var/static/loaded = load_ext(DOGMOS, "byond:groups_hook_ffi")
	return call_ext(loaded)(src, remaining)

/// Returns: If this cycle is interrupted by overtiming or not. Calls all outstanding callbacks created by other processes, usually ones that can't run on other threads and only the main thread.
/datum/controller/subsystem/air/proc/finish_turf_processing_auxtools(time_remaining)
	var/static/loaded = load_ext(DOGMOS, "byond:finish_process_turfs_ffi")
	return call_ext(loaded)(time_remaining)

/// Returns: If this cycle is interrupted by overtiming or not. Starts a processing turfs cycle.
/datum/controller/subsystem/air/proc/process_turfs_auxtools(remaining)
	var/static/loaded = load_ext(DOGMOS, "byond:process_turf_hook_ffi")
	return call_ext(loaded)(src, remaining)

/// Returns: If a processing thread is running or not.
/datum/controller/subsystem/air/proc/thread_running()
	var/static/loaded = load_ext(DOGMOS, "byond:thread_running_hook_ffi")
	return call_ext(loaded)()

/// For registering gases, do not touch this.
/proc/_auxtools_register_gas(gas)
	var/static/loaded = load_ext(DOGMOS, "byond:hook_register_gas_ffi")
	return call_ext(loaded)(gas)

/// For updating reagent gas fire products, do not use for now.
/proc/finalize_gas_refs()
	var/static/loaded = load_ext(DOGMOS, "byond:finalize_gas_refs_ffi")
	return call_ext(loaded)()

/// For updating reaction informations for auxmos, only call this when it is changed.
/datum/controller/subsystem/air/proc/auxtools_update_reactions()
	var/static/loaded = load_ext(DOGMOS, "byond:update_reactions_ffi")
	return call_ext(loaded)()

/// Returns: the number of reactions Dogmos accepted at init. Meridian: exists purely so DM can
/// assert across the FFI that the reaction table actually crossed, rather than only that DM built
/// one - see /datum/unit_test/dogmos_registration.
/proc/dogmos_reaction_count()
	var/static/loaded = load_ext(DOGMOS, "byond:dogmos_reaction_count_ffi")
	return call_ext(loaded)()

/// Registers gases, and get reaction infos for auxmos, only call when ssair is initing.
/proc/auxtools_atmos_init(gas_data)
	var/static/loaded = load_ext(DOGMOS, "byond:hook_init_ffi")
	return call_ext(loaded)(gas_data)

/turf/return_temperature()
	var/static/loaded = load_ext(DOGMOS, "byond:hook_turf_temperature_ffi")
	return call_ext(loaded)(src)

/datum/controller/subsystem/air/proc/process_turf_heat()
	var/static/loaded = load_ext(DOGMOS, "byond:process_heat_notify_ffi")
	return call_ext(loaded)(src)

