<#
	Builds Dogmos from the sibling fork, regenerates bindings.dm, and vendors the DLL.

	Run from anywhere. Does NOT need an elevated shell.

	Why this exists: a plain `cargo build` in this repo's tooling fails two ways that are easy to
	forget - the shell environment predates the rustup install (so cargo is not on PATH), and
	byondapi-sys refuses to compile for the x86_64 host, so every cargo command needs an explicit
	--target.

	code\__DEFINES\dogmos_bindings.dm is GENERATED by `cargo test generate_binds`, not hand-owned.
	It was hand-edited once (to rename colliding procs) and that edit rotted the moment the fork
	regenerated - see the 2026-08-13 postmortem in the plan. This script now DIFFS the generated
	output against the vendored copy and refuses to silently overwrite it: change the Rust
	#[byondapi::bind("...")] attribute or doc comment instead, so the generator emits what the game
	repo actually needs, then re-run with -AcceptBindings once.
#>

[CmdletBinding()]
param(
	# Skip regenerating bindings.dm. Faster when only the DM side changed.
	[switch]$SkipBindings,
	# Skip copying dogmos.dll into the game repo.
	[switch]$SkipVendor,
	# Skip the post-build boot probe smoke test.
	[switch]$SkipSmoke,
	# Vendor bindings.dm even though it differs from the generator's output. Use once, after fixing
	# the Rust side to emit what's needed - never as a way to keep a hand-edit alive.
	[switch]$AcceptBindings
)

$ErrorActionPreference = 'Stop'

$DogmosRepo = 'C:\Users\Zoe\Documents\GitHub\aphelion-dogmos'
$GameRepo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$Target = 'i686-pc-windows-msvc'

# The tool shell may predate the toolchain install, so rebuild the environment from the registry.
$env:Path = [Environment]::GetEnvironmentVariable('Path', 'Machine') + ';' + [Environment]::GetEnvironmentVariable('Path', 'User')
$env:LIBCLANG_PATH = [Environment]::GetEnvironmentVariable('LIBCLANG_PATH', 'Machine')

if (-not (Test-Path $DogmosRepo)) {
	throw "Dogmos fork not found at $DogmosRepo. Clone https://github.com/AphelionDevelopment/aphelion-dogmos there."
}

Push-Location $DogmosRepo
try {
	$branch = (git rev-parse --abbrev-ref HEAD)

	# The fork's checkout has been switched out from under this twice now. On master the crate is
	# still named "auxmos", so an unguarded build there produces the wrong library - or, worse,
	# succeeds against upstream code that has none of our fixes.
	$expectedBranch = 'dogmos'
	if ($branch -ne $expectedBranch) {
		throw "Fork is on branch '$branch', expected '$expectedBranch'. Run: git -C `"$DogmosRepo`" checkout $expectedBranch"
	}
	$crateName = (Select-String -Path (Join-Path $DogmosRepo 'Cargo.toml') -Pattern '^name = "(.+)"' |
		Select-Object -First 1).Matches.Groups[1].Value
	if ($crateName -ne 'dogmos') {
		throw "Cargo.toml declares crate '$crateName', expected 'dogmos'. The checkout is not our fork's work."
	}

	Write-Host "=== Building Dogmos ($branch) for $Target ===" -ForegroundColor Cyan

	cargo build --release --target $Target
	if ($LASTEXITCODE -ne 0) { throw "cargo build failed with exit code $LASTEXITCODE" }

	$VendoredBindings = Join-Path $GameRepo 'code\__DEFINES\dogmos_bindings.dm'

	if (-not $SkipBindings) {
		Write-Host '=== Regenerating bindings.dm ===' -ForegroundColor Cyan
		# Must pass --target: byondapi-sys hard-errors on non-x86 targets, and the host is x86_64.
		cargo test --target $Target generate_binds
		if ($LASTEXITCODE -ne 0) { throw "bindings generation failed with exit code $LASTEXITCODE" }

		$generated = Join-Path $DogmosRepo 'bindings.dm'
		$procCount = (Select-String -Path $generated -Pattern '^/(proc|datum|turf)').Count
		Write-Host "bindings.dm: $procCount bound procs"
		# A generator that silently emits an empty/near-empty file (e.g. a broken macro attribute sweep)
		# would otherwise only be caught by the drift diff below - and -AcceptBindings skips that diff
		# entirely, so it would happily vendor a gutted bindings.dm. 40 is well under the real count
		# (63 as of the SSAIR_SUPERCONDUCTIVITY cutover) but well above "something is badly broken".
		if ($procCount -lt 40) {
			throw "Only $procCount bound procs generated (expected several dozen). generate_binds is almost certainly broken - do not vendor this, even with -AcceptBindings."
		}

		# byondapi emits binds in inventory/link order (byondapi-rs/src/binds.rs), which is not
		# guaranteed stable across toolchains - hence a SORTED comparison. Content drift is what we
		# care about, not line order.
		$delta = Compare-Object (Get-Content $generated | Sort-Object) `
		                        (Get-Content $VendoredBindings | Sort-Object)

		if ($delta) {
			Write-Host ''
			Write-Host '=== bindings.dm drift ===' -ForegroundColor Yellow
			$delta | ForEach-Object {
				$side = if ($_.SideIndicator -eq '<=') { 'generator only ' } else { 'vendored only  ' }
				Write-Host "  $side $($_.InputObject)"
			}
			if (-not $AcceptBindings) {
				throw @'
Generated bindings differ from code\__DEFINES\dogmos_bindings.dm.
This file is GENERATED. Do not hand-edit it - change the #[byondapi::bind("...")] attribute or the
Rust doc comment in the fork instead, so the generator emits what the game repo needs natively.
Once the Rust side is right, re-run with -AcceptBindings to vendor the new output.
'@
			}
			Copy-Item $generated $VendoredBindings -Force
			Write-Host "vendored bindings -> $VendoredBindings" -ForegroundColor Green
		} else {
			Write-Host 'bindings.dm: in sync with the vendored copy.' -ForegroundColor Green
		}
	}

	$built = Join-Path $DogmosRepo "target\$Target\release\dogmos.dll"

	# A cargo no-op leaves a stale DLL behind and every downstream check then tests the OLD library.
	# Compare against the newest source file, Cargo.toml, and Cargo.lock, not against "did cargo print
	# Finished" - a no-op build prints that too. This now runs regardless of -SkipVendor: it used to
	# live inside that block, which meant -SkipVendor silently disabled the one check that would catch
	# a stale build BEFORE the (still-run) post-build smoke test tested the wrong library.
	$newestSource = Get-ChildItem (Join-Path $DogmosRepo 'src') -Recurse -Include *.rs |
		Sort-Object LastWriteTime -Descending | Select-Object -First 1
	$cargoToml = Get-Item (Join-Path $DogmosRepo 'Cargo.toml')
	$cargoLock = Get-Item (Join-Path $DogmosRepo 'Cargo.lock') -ErrorAction SilentlyContinue
	$builtItem = Get-Item $built
	foreach ($src in @($newestSource, $cargoToml, $cargoLock)) {
		if ($src -and $builtItem.LastWriteTime -lt $src.LastWriteTime) {
			throw "dogmos.dll ($($builtItem.LastWriteTime)) is older than $($src.Name) ($($src.LastWriteTime)). The build did not actually rebuild - do not trust anything downstream of this."
		}
	}

	if (-not $SkipVendor) {
		$vendored = Join-Path $GameRepo 'dogmos.dll'
		Copy-Item $built $vendored -Force
		$builtHash = (Get-FileHash $built -Algorithm SHA256).Hash
		$vendHash = (Get-FileHash $vendored -Algorithm SHA256).Hash
		if ($builtHash -ne $vendHash) { throw "vendored DLL hash does not match the built DLL - the copy failed, or something is holding the old file open (is DreamDaemon still running?)." }
		Write-Host "vendored -> $vendored ($($builtItem.Length) bytes, sha256 $($builtHash.Substring(0,16))...)" -ForegroundColor Green
	}
}
finally {
	Pop-Location
}

if (-not $SkipSmoke) {
	Write-Host ''
	Write-Host '=== Post-build smoke test ===' -ForegroundColor Cyan
	& (Join-Path $PSScriptRoot 'boot_probe.ps1')
	if ($LASTEXITCODE -ne 0) { throw "Post-build smoke test failed (boot_probe exit $LASTEXITCODE). The library built, but the game does not boot with it." }
}

Write-Host 'Done.' -ForegroundColor Green
